import { StyleSheet } from "react-native";
import colors from "./Colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.PRIMARYCOLOR,
  },
  topCard: {
    marginHorizontal: "5%",
    marginTop: "7%",
    padding: "7%",
    justifyContent: "flex-start",
  },
  input: {
    marginHorizontal: "5%",
    marginTop: "5%",
    padding: "3%",
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  button: {
    backgroundColor: colors.CARDCOLOR,
    marginHorizontal: "5%",
    marginTop: "5%",
    padding: "3%",
    borderRadius: 10,
    justifyContent: "center",
  },
  lastbutton: {
    backgroundColor: colors.CARDCOLOR,
    marginHorizontal: "5%",
    marginTop: "5%",
    marginBottom: "10%",
    padding: "3%",
    borderRadius: 10,
    justifyContent: "center",
  },
  timeinput: {
    marginHorizontal: "1%",
    marginTop: "3%",
    padding: "3%",
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "lightgrey",
  },
  text: {
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
  },
  toptitle: {
    shadowColor: colors.SHADOWCOLOR,
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 25,
    elevation: 5,
  },
  largeInput: {
    marginHorizontal: "10%",
    marginTop: "5%",
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius: 10,
    padding: "2%",
    paddingTop: "2%",
    height: 100,
    textAlignVertical: "top",
  },
});
